### ISSUE TITLE
Useless promise? 

### ISSUE THREAD

**Issue by guillerp8** [AtlasFw/atl-core#8]
https://github.com/AtlasFw/atl-core/blob/6a01992b13511a1651fd26a173fbbe62d38fc2a7/server/hotreload.lua#L19

I think that this promise is useless in this context.

**Comment by BombayV** [comment]
Pretty sure he mentioned that he wasn’t done with the callbacks system.

**Comment by Germancitoz** [comment]
Yeah, its not necesary to do that, i will delete it

**Comment by Germancitoz** [comment]
I remove the promise, I will close the issue
